name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height in meters: "))
print("Name:", name)
print("Age:", age)
print("Height:", height)
print(f"your name is {name} and your age is {age} and your height is {height}")
